shader1: shader1.cpp glad.o
	g++ shader1.cpp glad.o -o shader1 -lglut -lGL -lGLU -lglfw3 -lGL -lX11 -lpthread -lXrandr -lXi -ldl

shader2: shader2.cpp glad.o
	g++ shader2.cpp glad.o -o shader2 -lglut -lGL -lGLU -lglfw3 -lGL -lX11 -lpthread -lXrandr -lXi -ldl

shader3: shader3.cpp glad.o
	g++ shader3.cpp glad.o -o shader3 -lglut -lGL -lGLU -lglfw3 -lGL -lX11 -lpthread -lXrandr -lXi -ldl

clean:
	rm -f shader1 
